In [ ]:
'''Create a null vector of size 5'''
import numpy as np
a=np.zeros(5)

In [ ]:
'''Create a null vector of size 10 but the fifth value which is 1'''
a=np.zeroes(10)
a[0]=1

In [16]:
# Reverse a vector (first element becomes last)
import numpy as np

n=int(input("Enter number"))
a=np.zeros(n)
i=0
for i in range(0,n) :

    a[i]=int(input("Enter elements"))

b=np.flip(a)
print(a)
print(b)

Enter number3
Enter elements2
Enter elements3
Enter elements4
[2. 3. 4.]
[4. 3. 2.]


In [20]:
#Create a 3x3 array with random values and find the minimum and maximum value
import numpy as np
rnd = np.random.default_rng()
a=rnd.random((3,3))
print(a)
print("Max ",a.max())
print("Min ",a.min())

[[0.4854946  0.14346694 0.89844304]
 [0.49720508 0.03763858 0.11632389]
 [0.20405002 0.52339297 0.57835708]]
Max  0.8984430360134384
Min  0.037638576184459316


In [ ]:
#Consider a (5,5,8) shape array, what is the index (x,y,z) of the 100th element
import numpy as np
rnd = np.random.default_rng()
a=rnd.random((5,5,8))
print(a)
n=0
z=0
i=0
j=0
k=0
while (n!=100) :
    i=0
    while (i<5) :
        j=0
        while (j<5):
            k=0
            while (k<8) :
                n=n+1
                if(n==100):
                    print("index is (",i," , ",j," , ",k,")")
                    break
                k=k+1
            j=j+1
        i=i+1
        
    
                
            
    


[[[0.71288821 0.27550385 0.52281199 0.60021545 0.60478987 0.21132525
   0.84303575 0.45041552]
  [0.85761303 0.32355822 0.33357793 0.07842738 0.43800329 0.81981925
   0.46386446 0.22344007]
  [0.65462865 0.18471757 0.57893797 0.07632748 0.9440707  0.52356071
   0.601635   0.84640774]
  [0.30130977 0.76453762 0.54082385 0.79059969 0.10331035 0.16206373
   0.11184914 0.34876529]
  [0.30793856 0.41778076 0.90057688 0.61589464 0.08524194 0.02842021
   0.31889272 0.31315374]]

 [[0.63869219 0.46957133 0.02849443 0.81740355 0.1483081  0.1053387
   0.87770184 0.59859576]
  [0.82216504 0.83713393 0.37197144 0.53674602 0.8260643  0.84861041
   0.31707995 0.09395631]
  [0.97195124 0.81560135 0.01997339 0.59091302 0.37996794 0.81435113
   0.98413911 0.76528136]
  [0.89257044 0.36148801 0.97729008 0.05276686 0.36486848 0.46942199
   0.78800112 0.95406701]
  [0.77489449 0.87940883 0.27210875 0.19225808 0.89695553 0.82246911
   0.69979982 0.57157718]]

 [[0.98455999 0.9049438  0.73760777 0.40786103 

In [4]:
#Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates
import numpy as np
import math as m
rnd = np.random.default_rng()
a=rnd.random((10,2))
print("Cartesian coordinates : \n",a)
i=0
l=[]
while i<10 :
    r2=(a[i][0]*a[i][0])+(a[i][1]*a[i][1])
    r=m.sqrt(r2)
    s=(a[i][1]/a[i][0])
    th=m.atan(s)
    l2=[r,th]
    l.append(l2)
    i=i+1
print("Polar : ",l)

Cartesian coordinates : 
 [[0.97165085 0.89468095]
 [0.5751397  0.18733828]
 [0.28384628 0.39581808]
 [0.81017713 0.00168627]
 [0.86164711 0.15680151]
 [0.10467976 0.39244252]
 [0.81906187 0.34370672]
 [0.67097174 0.46738007]
 [0.98458888 0.51110967]
 [0.21947659 0.78828527]]
Cartesian :  [[1.3208176924344408, 0.7441802526108764], [0.6048812349348698, 0.3148889162135169], [0.4870735709989123, 0.9486772304821602], [0.810178884104884, 0.002081361501541338], [0.875798179207847, 0.180008972230869], [0.4061637415799262, 1.3101263297333459], [0.888254835220416, 0.39731736559648206], [0.8177085093936823, 0.6084215267572775], [1.1093459169940576, 0.47881825941767975], [0.8182686813773974, 1.2992507552078596]]
